'use client'

import React, { useState, useEffect } from 'react'
import { Button } from '@kunal-ak23/edudron-ui-components'

interface Question {
  id: string
  text: string
  type: 'LIKERT' | 'FORCED_CHOICE' | 'MICRO_SUBJECTIVE'
  options?: string[]
  module: string
  order: number
  totalQuestions?: number
  currentQuestionNumber?: number
}

interface GamifiedPsychometricTestProps {
  sessionId: string
  onComplete: () => void
  onAnswerSubmit: (answer: string) => Promise<void>
  isLoading?: boolean
}

const DISCLAIMER_TEXT = "This assessment is generated by an AI system. No human counselor has reviewed individual results. Results are suggestions only and non-binding. Students should discuss decisions with parents/guardians/counselors."

// Gamification elements
const MILESTONES = [
  { question: 5, message: "🎉 Great start! You're on a roll!", emoji: "🌟" },
  { question: 10, message: "🔥 Halfway through the basics! Keep going!", emoji: "💪" },
  { question: 18, message: "🎊 Core questions done! Time for personalized questions!", emoji: "🚀" },
  { question: 25, message: "⭐ Almost there! You're doing amazing!", emoji: "✨" },
  { question: 30, message: "🏆 Final stretch! You've got this!", emoji: "🎯" }
]

export function GamifiedPsychometricTest({
  sessionId,
  onComplete,
  onAnswerSubmit,
  isLoading = false
}: GamifiedPsychometricTestProps) {
  const [currentQuestion, setCurrentQuestion] = useState<Question | null>(null)
  const [selectedAnswer, setSelectedAnswer] = useState<string>('')
  const [textAnswer, setTextAnswer] = useState<string>('')
  const [showDisclaimer, setShowDisclaimer] = useState(true)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [points, setPoints] = useState(0)
  const [showMilestone, setShowMilestone] = useState(false)
  const [milestoneMessage, setMilestoneMessage] = useState('')
  const [milestoneEmoji, setMilestoneEmoji] = useState('')
  const [answeredCount, setAnsweredCount] = useState(0)
  const [showCelebration, setShowCelebration] = useState(false)

  // Load current question
  useEffect(() => {
    if (sessionId && !showDisclaimer) {
      loadCurrentQuestion()
    }
  }, [sessionId, showDisclaimer])

  const loadCurrentQuestion = async () => {
    try {
      const apiClient = (await import('@/lib/api')).getApiClient()
      const response = await apiClient.get(`/api/psychometric-test/${sessionId}/question`)
      
      let questionData: any = null
      if (response && typeof response === 'object' && 'data' in response) {
        questionData = (response as any).data
      } else if (response && typeof response === 'object') {
        questionData = response
      } else {
        questionData = response
      }

      if (questionData && questionData.id) {
        setCurrentQuestion(questionData)
        setSelectedAnswer('')
        setTextAnswer('')
        setError(null)
        
        // Check for milestone
        const currentQ = questionData.currentQuestionNumber || 0
        const milestone = MILESTONES.find(m => m.question === currentQ)
        if (milestone) {
          setMilestoneMessage(milestone.message)
          setMilestoneEmoji(milestone.emoji)
          setShowMilestone(true)
          setTimeout(() => setShowMilestone(false), 3000)
        }
        
        // Update answered count based on question number (for stable progress)
        // Use currentQuestionNumber - 1 because we're about to answer this question
        if (questionData.currentQuestionNumber) {
          const newCount = questionData.currentQuestionNumber - 1
          if (newCount >= answeredCount) {
            setAnsweredCount(newCount)
          }
        } else if (questionData.order) {
          // Fallback to order if currentQuestionNumber not available
          const newCount = questionData.order - 1
          if (newCount >= answeredCount) {
            setAnsweredCount(newCount)
          }
        }
      } else {
        setError('No more questions available. Please complete the test.')
      }
    } catch (err: any) {
      console.error('Failed to load question:', err)
      if (err.response?.status === 404 || err.response?.status === 400) {
        setError('Test appears to be completed. Redirecting to results...')
        setTimeout(() => {
          onComplete()
        }, 2000)
      } else {
        setError('Failed to load question. Please try again.')
      }
    }
  }

  const handleAnswerSelect = (answer: string) => {
    setSelectedAnswer(answer)
    setError(null)
    // Add points for engagement
    setPoints(prev => prev + 10)
  }

  const handleSubmit = async () => {
    if (!currentQuestion) return

    let answerValue = ''
    if (currentQuestion.type === 'MICRO_SUBJECTIVE') {
      answerValue = textAnswer.trim()
      if (!answerValue) {
        setError('Please enter your answer')
        return
      }
    } else {
      answerValue = selectedAnswer
      if (!answerValue) {
        setError('Please select an answer')
        return
      }
    }

    try {
      setIsSubmitting(true)
      setError(null)
      
      // Celebration animation
      setShowCelebration(true)
      setTimeout(() => setShowCelebration(false), 1000)
      
      await onAnswerSubmit(answerValue)
      
      // Points for completing a question
      setPoints(prev => prev + 50)
      
      // Clear answers and load next question (answered count will update from question data)
      setSelectedAnswer('')
      setTextAnswer('')
      await loadCurrentQuestion()
    } catch (err: any) {
      console.error('Failed to submit answer:', err)
      if (err.response?.status === 400 && err.response?.data?.message?.includes('completed')) {
        setError('Test is already completed. Redirecting to results...')
        setTimeout(() => {
          onComplete()
        }, 2000)
      } else {
        setError('Failed to submit answer. Please try again.')
      }
    } finally {
      setIsSubmitting(false)
    }
  }

  const handleDisclaimerAccept = () => {
    setShowDisclaimer(false)
  }

  if (showDisclaimer) {
    return (
      <div className="max-w-3xl mx-auto p-6 bg-gradient-to-br from-blue-50 to-purple-50 rounded-xl shadow-lg border-2 border-blue-200">
        <div className="mb-6">
          <div className="text-center mb-6">
            <div className="text-6xl mb-4">🎯</div>
            <h2 className="text-3xl font-bold text-gray-900 mb-2">Discover Your Path</h2>
            <p className="text-lg text-gray-600">Let&apos;s find out what career path suits you best!</p>
          </div>
          <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 mb-6 rounded-lg">
            <div className="flex">
              <div className="flex-shrink-0">
                <svg className="h-5 w-5 text-yellow-400" viewBox="0 0 20 20" fill="currentColor">
                  <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                </svg>
              </div>
              <div className="ml-3">
                <p className="text-sm text-yellow-700">
                  <strong>Important:</strong> {DISCLAIMER_TEXT}
                </p>
              </div>
            </div>
          </div>
          <div className="flex justify-center">
            <Button 
              onClick={handleDisclaimerAccept} 
              className="px-8 py-3 text-lg font-semibold bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white rounded-lg shadow-lg transform hover:scale-105 transition-all"
            >
              Let&apos;s Begin! 🚀
            </Button>
          </div>
        </div>
      </div>
    )
  }

  if (!currentQuestion) {
    return (
      <div className="max-w-3xl mx-auto p-6 bg-white rounded-lg shadow-md text-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600 mx-auto mb-4"></div>
        <p className="text-gray-600">Loading your next question...</p>
      </div>
    )
  }

  // Calculate progress more accurately - use answered count + 1 for current question
  const totalQuestions = currentQuestion.totalQuestions || 30
  // Use the higher of currentQuestionNumber or answeredCount + 1 to prevent going backwards
  const currentQNum = Math.max(
    currentQuestion.currentQuestionNumber || 0,
    answeredCount + 1
  )
  const progress = Math.min(100, Math.max(0, Math.round((currentQNum / totalQuestions) * 100)))

  const phase = currentQuestion.module === 'CORE' ? 'Core Questions' : 'Personalized Questions'

  return (
    <div className="max-w-4xl mx-auto">
      {/* Gamification Header */}
      <div className="mb-6 bg-gradient-to-r from-blue-600 to-purple-600 rounded-xl p-6 text-white shadow-lg">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h3 className="text-2xl font-bold mb-1">Career Discovery Journey</h3>
            <p className="text-blue-100">{phase}</p>
          </div>
          <div className="text-right">
            <div className="text-3xl font-bold">{points}</div>
            <div className="text-sm text-blue-100">Points</div>
          </div>
        </div>
        
        {/* Progress Bar with Animation */}
        <div className="mb-2">
          <div className="flex justify-between text-sm mb-2">
            <span>Question {currentQNum} of {totalQuestions}</span>
            <span className="font-semibold">{progress}% Complete</span>
          </div>
          <div className="w-full bg-white/20 rounded-full h-4 overflow-hidden">
            <div
              className="bg-white h-4 rounded-full transition-all duration-500 ease-out shadow-lg"
              style={{ width: `${progress}%` }}
            >
              <div className="h-full bg-gradient-to-r from-yellow-300 to-yellow-400 animate-pulse"></div>
            </div>
          </div>
        </div>
      </div>

      {/* Milestone Celebration */}
      {showMilestone && (
        <div className="mb-4 animate-bounce">
          <div className="bg-gradient-to-r from-yellow-400 to-orange-400 rounded-lg p-4 text-center shadow-lg">
            <div className="text-4xl mb-2">{milestoneEmoji}</div>
            <p className="text-white font-bold text-lg">{milestoneMessage}</p>
          </div>
        </div>
      )}

      {/* Question Card */}
      <div className="bg-white rounded-xl shadow-xl p-8 border-2 border-gray-100 hover:border-blue-300 transition-all">
        {/* Celebration Animation */}
        {showCelebration && (
          <div className="fixed inset-0 pointer-events-none z-50 flex items-center justify-center">
            <div className="text-6xl animate-bounce">🎉</div>
          </div>
        )}

        <div className="mb-6">
          <div className="flex items-start mb-4">
            <div className="bg-gradient-to-br from-blue-100 to-purple-100 rounded-full p-4 mr-4 flex-shrink-0">
              <span className="text-3xl">💭</span>
            </div>
            <div className="flex-1">
              <div className="flex items-center mb-2">
                <span className="text-xs bg-gradient-to-r from-purple-500 to-pink-500 text-white px-3 py-1 rounded-full font-semibold mr-2">
                  ✨ Personalized for You
                </span>
              </div>
              <h2 className="text-2xl font-bold text-gray-900 leading-relaxed">
                {currentQuestion.text}
              </h2>
            </div>
          </div>

          {/* Error Message */}
          {error && (
            <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg text-red-700 text-sm animate-shake">
              {error}
            </div>
          )}

          {/* Answer Options with Gamification */}
          {currentQuestion.type === 'LIKERT' && currentQuestion.options && (
            <div className="space-y-3">
              {currentQuestion.options.map((option, index) => {
                const isSelected = selectedAnswer === option
                return (
                  <button
                    key={index}
                    onClick={() => handleAnswerSelect(option)}
                    disabled={isSubmitting || isLoading}
                    className={`w-full p-5 text-left rounded-xl border-2 transition-all transform ${
                      isSelected
                        ? 'border-blue-500 bg-gradient-to-r from-blue-50 to-purple-50 text-blue-900 scale-105 shadow-lg'
                        : 'border-gray-200 bg-white text-gray-700 hover:border-blue-300 hover:bg-blue-50 hover:scale-102'
                    } ${isSubmitting || isLoading ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'} ${
                      isSelected ? 'ring-4 ring-blue-200' : ''
                    }`}
                  >
                    <div className="flex items-center">
                      <div className={`w-6 h-6 rounded-full border-2 mr-4 flex items-center justify-center ${
                        isSelected
                          ? 'border-blue-600 bg-blue-600'
                          : 'border-gray-300'
                      }`}>
                        {isSelected && (
                          <svg className="w-4 h-4 text-white" fill="currentColor" viewBox="0 0 20 20">
                            <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                          </svg>
                        )}
                      </div>
                      <span className="font-semibold text-lg">{option}</span>
                      {isSelected && <span className="ml-auto text-2xl">✨</span>}
                    </div>
                  </button>
                )
              })}
            </div>
          )}

          {currentQuestion.type === 'FORCED_CHOICE' && currentQuestion.options && (
            <div className="grid grid-cols-2 gap-4">
              {currentQuestion.options.map((option, index) => {
                const isSelected = selectedAnswer === option
                return (
                  <button
                    key={index}
                    onClick={() => handleAnswerSelect(option)}
                    disabled={isSubmitting || isLoading}
                    className={`p-6 text-center rounded-xl border-2 transition-all transform ${
                      isSelected
                        ? 'border-blue-500 bg-gradient-to-r from-blue-50 to-purple-50 text-blue-900 scale-105 shadow-lg ring-4 ring-blue-200'
                        : 'border-gray-200 bg-white text-gray-700 hover:border-blue-300 hover:bg-blue-50 hover:scale-102'
                    } ${isSubmitting || isLoading ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'}`}
                  >
                    <div className="text-3xl mb-2">{isSelected ? '✅' : index === 0 ? '🔵' : '🟢'}</div>
                    <span className="font-semibold">{option}</span>
                  </button>
                )
              })}
            </div>
          )}

          {currentQuestion.type === 'MICRO_SUBJECTIVE' && (
            <div>
              <textarea
                value={textAnswer}
                onChange={(e) => {
                  setTextAnswer(e.target.value)
                  setError(null)
                }}
                placeholder="Type your answer here (one word or short phrase)..."
                disabled={isSubmitting || isLoading}
                rows={3}
                maxLength={100}
                className="w-full px-4 py-3 border-2 border-gray-300 rounded-xl focus:outline-none focus:ring-4 focus:ring-blue-200 focus:border-blue-500 resize-none disabled:bg-gray-100 disabled:cursor-not-allowed text-lg"
              />
              <div className="mt-2 flex justify-between text-sm">
                <span className="text-gray-500">Keep it short and simple!</span>
                <span className={`font-semibold ${textAnswer.length > 80 ? 'text-orange-500' : 'text-gray-500'}`}>
                  {textAnswer.length}/100
                </span>
              </div>
            </div>
          )}
        </div>

        {/* Submit Button with Animation */}
        <div className="flex justify-end">
          <Button
            onClick={handleSubmit}
            disabled={isSubmitting || isLoading || (!selectedAnswer && !textAnswer.trim())}
            className={`px-8 py-3 text-lg font-semibold rounded-xl shadow-lg transform transition-all ${
              (!selectedAnswer && !textAnswer.trim()) || isSubmitting || isLoading
                ? 'opacity-50 cursor-not-allowed'
                : 'hover:scale-105 active:scale-95 bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700'
            }`}
          >
            {isSubmitting ? (
              <span className="flex items-center">
                <span className="animate-spin mr-2">⏳</span>
                Submitting...
              </span>
            ) : (
              <span className="flex items-center">
                Next Question <span className="ml-2">➡️</span>
              </span>
            )}
          </Button>
        </div>
      </div>

      {/* Fun Stats Footer */}
      <div className="mt-6 bg-gray-50 rounded-xl p-4 flex justify-around text-center">
        <div>
          <div className="text-2xl font-bold text-blue-600">{answeredCount}</div>
          <div className="text-sm text-gray-600">Questions Answered</div>
        </div>
        <div>
          <div className="text-2xl font-bold text-purple-600">{points}</div>
          <div className="text-sm text-gray-600">Points Earned</div>
        </div>
        <div>
          <div className="text-2xl font-bold text-green-600">{progress}%</div>
          <div className="text-sm text-gray-600">Complete</div>
        </div>
      </div>
    </div>
  )
}
