'use client'

import React, { useState, useEffect } from 'react'
import { Button } from '@kunal-ak23/edudron-ui-components'

interface Question {
  id: string
  text: string
  type: 'LIKERT' | 'FORCED_CHOICE' | 'MICRO_SUBJECTIVE'
  options?: string[]
  module: string
  order: number
  totalQuestions?: number
  currentQuestionNumber?: number
}

interface HybridPsychometricTestProps {
  sessionId: string
  onComplete: () => void
  onAnswerSubmit: (answer: string) => Promise<void>
  isLoading?: boolean
}

const DISCLAIMER_TEXT = "This assessment is generated by an AI system. No human counselor has reviewed individual results. Results are suggestions only and non-binding. Students should discuss decisions with parents/guardians/counselors."

export function HybridPsychometricTest({
  sessionId,
  onComplete,
  onAnswerSubmit,
  isLoading = false
}: HybridPsychometricTestProps) {
  const [currentQuestion, setCurrentQuestion] = useState<Question | null>(null)
  const [selectedAnswer, setSelectedAnswer] = useState<string>('')
  const [textAnswer, setTextAnswer] = useState<string>('')
  const [showDisclaimer, setShowDisclaimer] = useState(true)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  // Load current question
  useEffect(() => {
    if (sessionId && !showDisclaimer) {
      loadCurrentQuestion()
    }
  }, [sessionId, showDisclaimer])

  const loadCurrentQuestion = async () => {
    try {
      const apiClient = (await import('@/lib/api')).getApiClient()
      const response = await apiClient.get(`/api/psychometric-test/${sessionId}/question`)
      
      let questionData: any = null
      if (response && typeof response === 'object' && 'data' in response) {
        questionData = (response as any).data
      } else if (response && typeof response === 'object') {
        questionData = response
      } else {
        questionData = response
      }

      if (questionData && questionData.id) {
        setCurrentQuestion(questionData)
        setSelectedAnswer('')
        setTextAnswer('')
        setError(null)
      } else {
        // No more questions - test might be complete
        // Don't auto-complete, let user finish naturally
        setError('No more questions available. Please complete the test.')
      }
    } catch (err: any) {
      console.error('Failed to load question:', err)
      if (err.response?.status === 404 || err.response?.status === 400) {
        // Test might be completed or no more questions
        setError('Test appears to be completed. Redirecting to results...')
        setTimeout(() => {
          onComplete()
        }, 2000)
      } else {
        setError('Failed to load question. Please try again.')
      }
    }
  }

  const handleAnswerSelect = (answer: string) => {
    setSelectedAnswer(answer)
    setError(null)
  }

  const handleSubmit = async () => {
    if (!currentQuestion) return

    let answerValue = ''
    if (currentQuestion.type === 'MICRO_SUBJECTIVE') {
      answerValue = textAnswer.trim()
      if (!answerValue) {
        setError('Please enter your answer')
        return
      }
    } else {
      answerValue = selectedAnswer
      if (!answerValue) {
        setError('Please select an answer')
        return
      }
    }

    try {
      setIsSubmitting(true)
      setError(null)
      await onAnswerSubmit(answerValue)
      
      // Clear answers and load next question
      setSelectedAnswer('')
      setTextAnswer('')
      await loadCurrentQuestion()
    } catch (err: any) {
      console.error('Failed to submit answer:', err)
      if (err.response?.status === 400 && err.response?.data?.message?.includes('completed')) {
        // Test is already completed
        setError('Test is already completed. Redirecting to results...')
        setTimeout(() => {
          onComplete()
        }, 2000)
      } else {
        setError('Failed to submit answer. Please try again.')
      }
    } finally {
      setIsSubmitting(false)
    }
  }

  const handleDisclaimerAccept = () => {
    setShowDisclaimer(false)
  }

  if (showDisclaimer) {
    return (
      <div className="max-w-3xl mx-auto p-6 bg-white rounded-lg shadow-md">
        <div className="mb-6">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">Career Guidance Assessment</h2>
          <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 mb-6">
            <div className="flex">
              <div className="flex-shrink-0">
                <svg className="h-5 w-5 text-yellow-400" viewBox="0 0 20 20" fill="currentColor">
                  <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                </svg>
              </div>
              <div className="ml-3">
                <p className="text-sm text-yellow-700">
                  <strong>Important Disclaimer:</strong>
                </p>
                <p className="text-sm text-yellow-700 mt-2">
                  {DISCLAIMER_TEXT}
                </p>
              </div>
            </div>
          </div>
          <div className="flex justify-end">
            <Button onClick={handleDisclaimerAccept} className="px-6">
              I Understand, Continue
            </Button>
          </div>
        </div>
      </div>
    )
  }

  if (!currentQuestion) {
    return (
      <div className="max-w-3xl mx-auto p-6 bg-white rounded-lg shadow-md text-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600 mx-auto mb-4"></div>
        <p className="text-gray-600">Loading question...</p>
      </div>
    )
  }

  const progress = currentQuestion.currentQuestionNumber && currentQuestion.totalQuestions
    ? Math.round((currentQuestion.currentQuestionNumber / currentQuestion.totalQuestions) * 100)
    : 0

  return (
    <div className="max-w-3xl mx-auto p-6 bg-white rounded-lg shadow-md">
      {/* Progress Bar */}
      {currentQuestion.totalQuestions && (
        <div className="mb-6">
          <div className="flex justify-between text-sm text-gray-600 mb-2">
            <span>Question {currentQuestion.currentQuestionNumber} of {currentQuestion.totalQuestions}</span>
            <span>{progress}%</span>
          </div>
          <div className="w-full bg-gray-200 rounded-full h-2">
            <div
              className="bg-primary-600 h-2 rounded-full transition-all duration-300"
              style={{ width: `${progress}%` }}
            ></div>
          </div>
        </div>
      )}

      {/* Question */}
      <div className="mb-6">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">
          {currentQuestion.text}
        </h2>

        {/* Error Message */}
        {error && (
          <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded text-red-700 text-sm">
            {error}
          </div>
        )}

        {/* Answer Options */}
        {currentQuestion.type === 'LIKERT' && currentQuestion.options && (
          <div className="space-y-3">
            {currentQuestion.options.map((option, index) => (
              <button
                key={index}
                onClick={() => handleAnswerSelect(option)}
                disabled={isSubmitting || isLoading}
                className={`w-full p-4 text-left rounded-lg border-2 transition-all ${
                  selectedAnswer === option
                    ? 'border-primary-600 bg-primary-50 text-primary-900'
                    : 'border-gray-200 bg-white text-gray-700 hover:border-primary-300 hover:bg-gray-50'
                } ${isSubmitting || isLoading ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'}`}
              >
                <div className="flex items-center">
                  <div className={`w-4 h-4 rounded-full border-2 mr-3 ${
                    selectedAnswer === option
                      ? 'border-primary-600 bg-primary-600'
                      : 'border-gray-300'
                  }`}>
                    {selectedAnswer === option && (
                      <div className="w-full h-full rounded-full bg-primary-600"></div>
                    )}
                  </div>
                  <span className="font-medium">{option}</span>
                </div>
              </button>
            ))}
          </div>
        )}

        {currentQuestion.type === 'FORCED_CHOICE' && currentQuestion.options && (
          <div className="space-y-3">
            {currentQuestion.options.map((option, index) => (
              <button
                key={index}
                onClick={() => handleAnswerSelect(option)}
                disabled={isSubmitting || isLoading}
                className={`w-full p-4 text-left rounded-lg border-2 transition-all ${
                  selectedAnswer === option
                    ? 'border-primary-600 bg-primary-50 text-primary-900'
                    : 'border-gray-200 bg-white text-gray-700 hover:border-primary-300 hover:bg-gray-50'
                } ${isSubmitting || isLoading ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'}`}
              >
                <div className="flex items-center">
                  <div className={`w-4 h-4 rounded-full border-2 mr-3 ${
                    selectedAnswer === option
                      ? 'border-primary-600 bg-primary-600'
                      : 'border-gray-300'
                  }`}>
                    {selectedAnswer === option && (
                      <div className="w-full h-full rounded-full bg-primary-600"></div>
                    )}
                  </div>
                  <span className="font-medium">{option}</span>
                </div>
              </button>
            ))}
          </div>
        )}

        {currentQuestion.type === 'MICRO_SUBJECTIVE' && (
          <div>
            <textarea
              value={textAnswer}
              onChange={(e) => {
                setTextAnswer(e.target.value)
                setError(null)
              }}
              placeholder="Type your answer here (one word or short phrase)"
              disabled={isSubmitting || isLoading}
              rows={3}
              maxLength={100}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent resize-none disabled:bg-gray-100 disabled:cursor-not-allowed"
            />
            <p className="mt-2 text-sm text-gray-500">
              {textAnswer.length}/100 characters
            </p>
          </div>
        )}
      </div>

      {/* Submit Button */}
      <div className="flex justify-end">
        <Button
          onClick={handleSubmit}
          disabled={isSubmitting || isLoading || (!selectedAnswer && !textAnswer.trim())}
          className="px-8"
        >
          {isSubmitting ? 'Submitting...' : 'Next'}
        </Button>
      </div>
    </div>
  )
}
